class TaskNames:
    SEARCH_KEYWORD_GENERATOR = "search_keyword_generator"
    RESTRICTION_GENERATOR = "restriction_generator"
    CRAWLER = "crawler"
    CHUNK_DIVISOR = "chunk_divisor"
    RELEVANCE_ESTIMATOR = "relevance_estimator"
    RELEVANCE_ESTIMATOR_SUBTASK = "relevance_estimator_subtask"
    MERGER = "merger"
    INSERT_TO_DATABASE = "insert_to_database"
    RESULT_GENERATOR = "result_generator"
    PLACE_KEYWORD_EXTRACTOR = "place_keyword_generator"
    PATH_KEYWORD_EXTRACTOR = "path_keyword_generator"
    PLACE_CRAWLER = "place_crawler"
    PATH_CRAWLER = "path_crawler"
    ASSO_SEARCH_GENERATOR = "asso_search_generator"
    SOCKETIO_EMIT = "socketio_emit"


class DataNames:
    USER_INPUT = "user_input"
    SEARCH_KEYWORDS = "search_keywords"
    RESTRICTIONS = "restrictions"
    CRAWLED_DATA = "crawled_data"
    CHUNK_DIVIDED_DATA = "chunk_divided_data"
    RELEVANCE_DATA = "relevance_data"
    MERGED_DATA = "merged_data"
    LINKS = "links"
    PLACE_KEYWORDS = "place_keywords"
    PATH_KEYWORDS = "path_keywords"
    PLACE_DATA = "place_data"
    PATHFINDING_DATA = "pathfinding_data"
    RESULT = "result"
    ASSOCIATED_SEARCH = "associated_search"
