class TaskNames:
    SEARCH_KEYWORD_GENERATOR = 'search_keyword_generator'
    RESTRICTION_GENERATOR = 'restriction_generator'
    CRAWLER = 'crawler'
    CHUNK_DIVISOR = 'chunk_divisor'
    RELEVANCE_ESTIMATOR = 'relevance_estimator'
    RELEVANCE_ESTIMATOR_SUBTASK = 'relevance_estimator_subtask'
    MERGER = 'merger'
    POI_NEEDS_GENERATOR = 'poi_needs_generator'
    RESULT_GENERATOR = 'result_generator'

class DataNames:
    USER_INPUT = 'user_input'
    SEARCH_KEYWORDS = 'search_keywords'
    RESTRICTIONS = 'restrictions'
    CRAWLED_DATA = 'crawled_data'
    CHUNK_DIVIDED_DATA = 'chunk_divided_data'
    RELEVANCE_DATA = 'relevance_data'
    MERGED_DATA = 'merged_data'
    LINKS = 'links'
    POI_NEEDS = 'poi_needs'
    RESULT = 'result'